# Generated by Django 5.0.1 on 2024-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_active',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
